import{a as p,S as y,i as u}from"./assets/vendor-BDaiwwc1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const h="https://pixabay.com/api",b="49031681-364093aaa4634c3b7924c5e31";async function f(o,e=1){const i=new URLSearchParams({key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:40});try{return(await p.get(`${h}?${i}`)).data}catch(r){throw console.error("Error fetching images:",r),new Error("Failed to fetch images")}}const w=new y(".gallery a",{captionsData:"alt",captionDelay:250,close:"true"});function m(o){const e=document.querySelector(".gallery"),i=o.map(r=>`
    <li class="gallery-item">
      <a class='gallery-link' href="${r.largeImageURL}">
        <img class="li-img" src="${r.webformatURL}" alt="${r.tags}" />
        <div class="li-text">
          <table class="table">
            <tr><td>Likes</td><td>Views</td><td>Comments</td><td>Downloads</td></tr>
            <tr><td>${r.likes}</td><td>${r.views}</td><td>${r.comments}</td><td>${r.downloads}</td></tr>
          </table>
        </div>
      </a>
    </li>
  `).join("");e.insertAdjacentHTML("beforeend",i),w.refresh()}const g=document.querySelector(".form"),L=document.querySelector(".input-search"),a=document.querySelector(".wait-msg"),l=document.querySelector(".load-more-btn");let n=1,c="";l.style.display="none";g.addEventListener("submit",async o=>{if(o.preventDefault(),c=L.value.trim(),!c){u.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",position:"topRight",title:"Error",titleColor:"#fff",message:"Please enter a search query"});return}a.innerHTML='Loading images... <span class="loader"></span>',document.querySelector(".gallery").innerHTML="",n=1;try{const e=await f(c,n);if(e.hits.length===0){u.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",position:"topRight",title:"Error",titleColor:"#fff",message:"No images found, please try another search!"});return}m(e.hits),a.textContent="",e.totalHits>n*40?l.style.display="block":l.style.display="none"}catch(e){a.textContent="Oops... something went wrong.",console.error(e)}g.reset()});l.addEventListener("click",async()=>{a.innerHTML='Loading more images... <span class="loader"></span>',n+=1;try{const o=await f(c,n);m(o.hits),a.textContent="",o.totalHits<=n*40&&(l.style.display="none",u.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",position:"topRight",title:"End of results",titleColor:"#fff",message:"We're sorry, but you've reached the end of search results"}));const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){a.textContent="Oops... something went wrong.",console.error(o)}});
//# sourceMappingURL=index.js.map
